- packages/lib/src/components/charts/lume-bar-chart/lume-bar-chart.stories.ts
- packages/lib/src/components/charts/lume-line-chart/lume-line-chart.stories.ts
- packages/lib/src/components/core/lume-chart/README.md
- packages/lib/src/components/core/lume-chart/lume-chart.spec.ts
- packages/lib/src/components/core/lume-chart/lume-chart.vue
- packages/lib/src/components/core/lume-tooltip/README.md
- packages/lib/src/components/core/lume-tooltip/lume-tooltip.spec.ts
- packages/lib/src/components/core/lume-tooltip/lume-tooltip.vue
- packages/lib/src/components/core/lume-tooltip/styles.scss
- packages/lib/src/composables/options.ts
- packages/lib/src/docs/storybook-helpers.ts
- packages/lib/src/types/events.ts
- packages/lib/test/config/setupTests.ts
Relates to #269 
The interaction events within lume tooltip is not captured. This PR aims to provide an option to capture pointer events in tooltip.
> Handling events in lume tooltip

- packages/lib/src/components/core/lume-axis/composables/lume-skip.ts
> - Increase safety margin from 15% to 20% in tick skip logic
>
> 🩹 Increase skip safety margin

- packages/lib/src/components/charts/lume-line-chart/lume-line-chart.stories.ts
- packages/lib/src/docs/storybook-data/base-data.ts
- packages/lib/src/utils/helpers.spec.ts
- packages/lib/src/utils/helpers.ts
Relates to #324 
Currently tooltips in grouped chart breaks whenever the number of data points between items in the group are different.
This PR covers:
- Checking if the data points for atleast one of the item is present before showing the tooltip. If so, the tooltip has to show up.
- Updated tests and stories to cover this scenario.
> Add a brief description
> 🐛 Added support for grouped charts with varied data points.

- packages/lib/src/components/charts/lume-alluvial-diagram/lume-alluvial-diagram.spec.ts
- packages/lib/src/components/groups/lume-alluvial-group/composables/alluvial-graph.ts
- packages/lib/src/components/groups/lume-alluvial-group/constants.ts
- packages/lib/src/components/groups/lume-alluvial-group/helpers.ts
- packages/lib/src/docs/storybook-data/alluvial-data.ts
Closes #328
> - Added a minimum height of 2px to the alluvial nodes
> - Added a -1px Y offset for nodes that have this 2px min. height
> - Fallback color is now `grey` if the node value is 0
>
> ✨ Add minimum node height & 0 value fallback color

- CHANGELOG.md
- package.json
- packages/vue2/package.json
- packages/vue3/package.json
- pnpm-lock.yaml
- ⬆️ Update storybook monorepo to v7.5.2 [`6337521`](https://github.com/Adyen/lume/commit/6337521401e1999303c5d48a3aa539f529252265)
- ⬆️ Update vue monorepo [`473c633`](https://github.com/Adyen/lume/commit/473c633b0e410cb999bc36330148b83902166fb0)
- ⬆️ Update dependency webpack to v5.89.0 [`006f790`](https://github.com/Adyen/lume/commit/006f790315bc163e9e0cf5348599c5c835f0757e)
- ⬆️ Update dependency vite to v4.5.0 [`95ae85d`](https://github.com/Adyen/lume/commit/95ae85d9cbbfea58065655a9a3a178306bfb8ebb)
- ⬆️ Update typescript-eslint monorepo to v5.62.0 [`f09a425`](https://github.com/Adyen/lume/commit/f09a4251430d7ad31cb997c65df1cc260d28046b)
- ⬆️ Update dependency @types/node to v18.18.7 [`4e7934a`](https://github.com/Adyen/lume/commit/4e7934a06e1bc23ef7c79dbe3370092f3b923997)
- ⬆️ …
> 🔖 Release v1.5.0

- CHANGELOG.md
- package.json
- packages/vue2/package.json
- packages/vue3/package.json
Relates to #324 
- Tooltip anchor was not generated for bar charts (grouped/stacked) at points where there was no data in few items of the group.
- Now creating tooltip anchors as many as the chart labels to handle such scenarios.
> 🔖 Release v1.5.1

- packages/lib/src/components/core/lume-chart/lume-chart.vue
* For grouped charts all the items need not have to be of same length.
* Marking index as invalid only if its greater than all the items.
>
> 🐛 External hover to check all items before marking index as invalid

- packages/lib/src/utils/helpers.spec.ts
- packages/lib/src/utils/helpers.ts
- packages/lib/src/utils/warnings.ts
* When the passed index is greater than ALL the items in the group, we're throwing an error currently.
* But this would result in chart not being rendered - so replacing it with console warning, similar to other hovered index warnings.
>
> 🚸 Replacing the error with warning if index is not present in group.

- packages/lib/src/components/charts/lume-bar-chart/lume-bar-chart.spec.ts
- packages/lib/src/components/charts/lume-grouped-bar-chart/lume-grouped-bar-chart.spec.ts
- packages/lib/src/components/charts/lume-line-chart/lume-line-chart.spec.ts
- packages/lib/src/components/charts/lume-line-chart/lume-line-chart.stories.ts
- packages/lib/src/components/charts/lume-single-bar-chart/lume-single-bar-chart.spec.ts
- packages/lib/src/components/charts/lume-stacked-bar-chart/lume-stacked-bar-chart.spec.ts
- packages/lib/src/components/charts/lume-stacked-bar-chart/lume-stacked-bar-chart.vue
- packages/lib/src/components/core/lume-chart/lume-chart.vue
- packages/lib/src/components/groups/lume-bar-group/composables/bar-mixin.ts
- packages/lib/src/components/groups/lume-bar-group/lume-bar-group.vue
- packages/lib/src/components/groups/lume-line-group/lume-line-group.vue
- packages/lib/src/composables/tooltip.spec.ts
- packages/lib/src/composables/tooltip.ts
- packages/lib/src/docs/storybook-data/base-data.ts
- packages/lib/src/utils/constants.ts
- packages/lib/src/utils/helpers.ts
- packages/lib/test/unit/reusable.test.ts
* Tooltip anchor attributes to be generated for all the data items.
* While grouping the bar chart, index was not considered into account as a result color of items in the group chart were getting messed up when items are not of equal length.
>
> 🐛 Handled missing data in lume charts

- packages/lib/src/components/core/lume-chart-legend/lume-chart-legend.vue
> - Fixes a console error when `lume-chart-legend` was used outside of a `lume-chart`
>
> 🐛 Fix add default value to isEmpty inject

- packages/lib/src/components/groups/lume-alluvial-group/lume-alluvial-group.vue
> - Added minimum height logic to the nodes deriving color from incoming links
> - Works by dividing the number of incoming links by the min. node height
> 🐛 Fix alluvial node min. height in derived nodes

- packages/lib/src/components/groups/lume-line-group/lume-line-group.vue
- packages/lib/src/composables/line-null-values.ts
- packages/lib/src/composables/line-values.ts
> - Fixed some cases where datasets will all `null` value would cause errors in the console
> - Fixed line group point positioning for all-null datasets
>
> 🐛 Fix unhandled line-group null value cases

- packages/lib/src/components/core/lume-axis/composables/lume-skip.ts
- packages/lib/src/components/core/lume-axis/lume-axis.vue
Fixes #369 
> - Passed the option ref instead of the static value to the useSkip composable
>
> 🐛 Make skip option reactive

- packages/lib/src/components/charts/lume-stacked-bar-chart/lume-stacked-bar-chart.spec.ts
- packages/lib/src/components/charts/lume-stacked-bar-chart/lume-stacked-bar-chart.vue
Fixes #374
> - Added computed scales for stacked bar chart that allow for prop override
>
> 🐛 Fix scale override in stacked bar chart

- packages/lib/src/components/core/lume-chart-legend/lume-chart-legend.vue
Closes #373
> Removed `v-if="!isEmpty"` in `lume-chart-legend`
>
> 🐛 Show chart legend even if values are empty

- packages/lib/src/components/charts/lume-bar-chart/lume-bar-chart.vue
- packages/lib/src/components/charts/lume-grouped-bar-chart/lume-grouped-bar-chart.spec.ts
- packages/lib/src/components/charts/lume-line-chart/lume-line-chart.spec.ts
- packages/lib/src/components/charts/lume-single-bar-chart/lume-single-bar-chart.spec.ts
- packages/lib/src/components/charts/lume-sparkline-chart/lume-sparkline-chart.vue
- packages/lib/src/components/charts/lume-stacked-bar-chart/lume-stacked-bar-chart.spec.ts
- packages/lib/src/components/core/lume-axis/lume-axis.vue
- packages/lib/src/components/core/lume-chart/lume-chart.vue
- packages/lib/src/components/groups/lume-alluvial-group/composables/alluvial-graph.ts
- packages/lib/src/components/groups/lume-bar-group/composables/stacked-mixin.ts
- packages/lib/src/composables/base.ts
- packages/lib/src/composables/scales.spec.ts
- packages/lib/src/composables/scales.ts
- packages/lib/src/docs/storybook-data/alluvial-data.ts
- packages/lib/src/docs/storybook-data/base-data.ts
- packages/lib/src/docs/storybook-data/sparkline-data.ts
Fixes #375
> - When one of the dimensions (data, labels) is empty, no longer generates a scale
>
> 🐛 Fix empty data/labels handling

- packages/lib/src/components/core/lume-chart/lume-chart.vue
- packages/lib/src/playground/synced-tooltip.stories.ts
Before, when trying to sync tooltips between two charts (like the example below), one of them would fly in instead of appear in the chart.
```vue
<lume-bar-chart
v-bind="args"
type="stacked"
:hovered-index="hoveredIndex"
@tooltip-opened="hoveredIndex = $event.index"
@tooltip-moved="hoveredIndex = $event.index"
@tooltip-closed="hoveredIndex = -1"
/>
<lume-bar-chart
v-bind="args"
type="stacked"
:hovered-index="hoveredIndex"
@tooltip-opened="hoveredIndex = $event.index"
@tooltip-moved="hoveredIndex = $event.index"
@tooltip-closed="hoveredIndex = -1"
/>
```
This was because the `handleExternalHover` in `<lume-chart>` was always calling `handleInternalHover` even if the external index was `-1` (or `null`).
This PR corrects that into checking if it should handle it as show or hide tooltip based …
> 🐛 Fix wrong assumption on external hover

- CHANGELOG.md
- package.json
- packages/vue2/package.json
- packages/vue3/package.json
- 🐛 Fix empty data/labels handling [`d5dca98`](https://github.com/Adyen/lume/commit/d5dca9899ea03a433672df32537bc107ccc23492)
- 🐛 Fix wrong assumption on external hover [`ca3f936`](https://github.com/Adyen/lume/commit/ca3f936e238467c7583a66242cf59fa3b714ed79)
- 🐛 Fix scale override in stacked bar chart [`a6ba301`](https://github.com/Adyen/lume/commit/a6ba3018e9299484f7349fcd0e384e85676c73df)
- 🐛 Show chart legend even if values are empty [`c953019`](https://github.com/Adyen/lume/commit/c953019721926a5dd3cdaa7d3fc0858e569db1d3)
- ✅ Update scales unit tests [`c418f6f`](https://github.com/Adyen/lume/commit/c418f6fe7d8498bda6d09bd19379aedaffc463da)
- 🔇 Remove console log [`58f5316`](https://github.com/Adyen/lume/commit/58f531652fae86041296dab56de0c9e72bd33894)
> 🔖 Release v1.6.6

- packages/lib/src/components/charts/lume-bar-chart/lume-bar-chart.vue
- packages/lib/src/components/core/lume-axis/lume-axis.vue
- packages/lib/src/components/groups/lume-bar-group/composables/bar-mixin.ts
- packages/lib/src/components/groups/lume-bar-group/composables/grouped-mixin.ts
- packages/lib/src/components/groups/lume-bar-group/composables/single-mixin.ts
- packages/lib/src/utils/errors.ts
- packages/lib/src/utils/helpers.ts
Fixes handling cases where the datasets have params but `values` is empty.
> 🐛 Fix handling datasets with empty values

- packages/lib/src/components/charts/lume-stacked-bar-chart/defaults.ts
- packages/lib/src/components/core/lume-tooltip/README.md
- packages/lib/src/components/core/lume-tooltip/lume-tooltip.spec.ts
- packages/lib/src/components/core/lume-tooltip/lume-tooltip.vue
- packages/lib/src/composables/options.ts
Closes #379
Added the `inverse` property and option to `<lume-tooltip>`. If true, the items rendered in the tooltip order is reversed.
Updated `<lume-stacked-bar-chart>` default options to reflect `inverse: true`, as per the design guidelines.
Also included a new unit test for this case and updated README documentation.
> ✨ Introduce inverse property/option in lume-tooltip

- packages/lib/src/components/charts/lume-stacked-bar-chart/defaults.ts
Removed `inverse:  true` from the horizontal stacked bar chart default options.
> 🩹 Fix the horizontal stacked bar chart default options

- packages/lib/src/components/groups/lume-alluvial-group/components/lume-alluvial-node-header/README.md
- packages/lib/src/components/groups/lume-alluvial-group/components/lume-alluvial-node-header/index.ts
- packages/lib/src/components/groups/lume-alluvial-group/components/lume-alluvial-node-header/lume-alluvial-node-header.vue
- packages/lib/src/components/groups/lume-alluvial-group/lume-alluvial-group.vue
- packages/lib/src/components/index.ts
Closes #387
Introduced a new component - `lume-alluvial-node-header`.
The alluvial group uses it and adds slots based on the `nodeHeaders` option.
Added documentation for `lume-alluvial-node-header`.
> ✨ Add lume-alluvial-node-header component

- packages/lib/src/components/charts/lume-alluvial-diagram/lume-alluvial-diagram.stories.ts
- packages/lib/src/components/charts/lume-bar-chart/lume-bar-chart.stories.ts
- packages/lib/src/components/charts/lume-line-chart/lume-line-chart.stories.ts
- packages/lib/src/components/core/lume-chart/README.md
- packages/lib/src/components/core/lume-chart/lume-chart.spec.ts
- packages/lib/src/components/core/lume-chart/lume-chart.vue
- packages/lib/src/components/core/lume-tooltip/README.md
- packages/lib/src/components/core/lume-tooltip/lume-tooltip.vue
- packages/lib/src/playground/custom-tooltip.stories.ts
Closes #395 
- Added `opened` prop to `lume-tooltip` (defaults to `false`)
- Now adds/removes the animation class on Popper create/destroy (no more flying from the corner)
> **Note:** It still works the old way too (e.g. `<lume-tooltip v-if="opened" />`), but it's not recommended.
Users can now do
```vue
<template #tooltip="tooltipProps">
<lume-tooltip v-bind="tooltipProps">
...
</lume-tooltip>
</template>
```
and it works out-of-the-box.
> 🚸 Improve lume-tooltip usability by introducing opened prop

- packages/lib/src/components/charts/lume-alluvial-diagram/lume-alluvial-diagram.vue
- packages/lib/src/components/charts/lume-grouped-bar-chart/lume-grouped-bar-chart.vue
- packages/lib/src/components/charts/lume-line-chart/lume-line-chart.vue
- packages/lib/src/components/charts/lume-single-bar-chart/lume-single-bar-chart.vue
- packages/lib/src/components/charts/lume-stacked-bar-chart/lume-stacked-bar-chart.vue
- packages/lib/src/components/core/lume-chart/lume-chart.vue
- packages/lib/src/composables/events.ts
- packages/lib/src/docs/storybook-helpers.ts
- packages/lib/src/playground/hovered-index-two-way-binding.stories.ts
- packages/lib/src/playground/synced-tooltip.stories.ts
- packages/lib/src/types/events.ts
Closes #394
Added an `update` event for `hoveredIndex` (`update:hoveredIndex`) so that users can two-way bind this property.
Vue 2 example:
```vue
<lume-line-chart v-bind:hoveredIndex.sync="customIndex" />
<script setup>
const customIndex = ref(-1);
</script>
```
Vue 3 example:
```vue
<lume-line-chart v-model:hoveredIndex="customIndex" />
<script setup>
const customIndex = ref(-1);
</script>
```
- Updated charts to also inherit attributes (`$attrs`) - needed to properly listen to `update:*` event(s)
- Added a playground Story and updates the synced tooltips Story
> ✨ Add update event for hoveredIndex

- CHANGELOG.md
- package.json
- packages/vue2/package.json
- packages/vue3/package.json
- ✨ Add update event for hoveredIndex [`ecfa912`](https://github.com/Adyen/lume/commit/ecfa912bb291f053b93754107447dedd76b9b956)
- 🚸 Improve lume-tooltip usability by introducing opened prop [`e76fa5a`](https://github.com/Adyen/lume/commit/e76fa5a67de11185f93a12842a270d04a5d9b27d)
- ✅ Update LumeChart unit tests [`f534a3b`](https://github.com/Adyen/lume/commit/f534a3b673d852c9e749140a51e119e1a9dd5164)
> 🔖 Release v1.9.0

- packages/lib/src/utils/constants.ts
Constants were missing the sequential neutral (grey) colors, and black/white.
--
> 🐛 Add missing color values in constants

- packages/lib/src/components/core/lume-chart/lume-chart.vue
Currently consumers cannot act upon resize for any of the lume charts. Emitting resize event from lume chart so that all the charts will have that emit.
> 🩹 Emitting resize event from lume chart

- packages/lib/src/components/core/lume-chart/lume-chart.spec.ts
- packages/lib/src/components/core/lume-tooltip/lume-tooltip.spec.ts
- packages/lib/src/components/core/lume-tooltip/lume-tooltip.vue
Using `v-show` on tooltip would force consumers (especially custom tooltip implementations) to handle `hoveredIndex = -1` cases (when tooltip is *not* shown).  
This way there's no need to handle those cases because the tooltip will only render if `hoveredIndex > -1`
--
> 🐛 Fix lume-tooltip use v-if instead of v-show

- packages/lib/src/components/core/lume-bar/composables/bar-transition.ts
Fixes #430 
Converted the px value for each bar `transform-origin` to `rem`.
Reference: https://github.com/carbon-design-system/icons-motion/issues/103
> 🐛 Convert bar transform-origin to rem

- packages/lib/src/components/core/lume-chart-container/README.md
- packages/lib/src/components/core/lume-chart-container/lume-chart-container.vue
- packages/lib/src/components/core/lume-chart/lume-chart.vue
A bar chart with `orientation: 'horizontal'` and `noMinSize: true` was rendering with `0px` height instead of the correct height based on bar height and count.
--
> 🐛 Horizontal bar charts without minimum size not calculating height on initial render

- CHANGELOG.md
- package.json
- packages/vue2/package.json
- packages/vue3/package.json
- 🐛 Horizontal bar charts without minimum size not calculating height on initial render [`b9818ca`](https://github.com/Adyen/lume/commit/b9818cab1f76e721d5f6835934f264568e0ff878)
> 🔖 Release v1.10.2

- packages/vue2/package.json
- packages/vue3/package.json
Fixes problem when importing components from `@adyen/lume`:
--
> 🐛 Fix type declaration exports

- CHANGELOG.md
- package.json
- packages/vue2/package.json
- packages/vue3/package.json
- 🐛 Fix type declaration exports [`0781e5a`](https://github.com/Adyen/lume/commit/0781e5a3e1e8285a8e3ecb097913f5d83032b5f9)
> 🔖 Release v1.10.3

- packages/lib/src/components/core/lume-chart/lume-chart.spec.ts
- packages/lib/src/components/core/lume-chart/lume-chart.vue
Assumes datasets filled with `null` values as an empty chart.
--
> 🐛 Assume null data as empty

- packages/lib/src/components/core/lume-axis/lume-axis.vue
Fixes axes alignment when scale `domain` is zeros. This happens, for instance, when all dataset values are `0`.
--
> 🐛 Fix axis alignment when scale domain is 0 to 0

- packages/lib/src/components/core/lume-bar/composables/bar-transition.ts
This reverts commit 810ffb3e365ec2b4918ae63c2944b7f830b75827.
Add a brief description
As per Safari's bugfix, `transform-origin` should be reverted and set in `px`.
Relevant links:
- https://bugs.webkit.org/show_bug.cgi?id=133150
- https://github.com/WebKit/WebKit/commit/c78d507eeee2bb3be38e5f5129c3af9f497bbd71
- https://developer.apple.com/documentation/safari-release-notes/safari-18_2-release-notes#Resolved-Issues
> ⏪️ Revert "Convert bar transform-origin to rem"
