packages/vue2/.storybook/manager.ts, packages/vue3/.storybook/manager.ts
> - Fix the `brandImage` path in `manager.ts`
>
=> 🩹 Fix Storybook sidebar logo

packages/lib/src/components/charts/lume-alluvial-diagram/README.md, packages/lib/src/components/charts/lume-alluvial-diagram/lume-alluvial-diagram.spec.ts, packages/lib/src/components/charts/lume-alluvial-diagram/lume-alluvial-diagram.stories.ts, packages/lib/src/components/groups/lume-alluvial-group/composables/alluvial-graph.ts, packages/lib/src/components/groups/lume-alluvial-group/lume-alluvial-group.vue, packages/lib/src/docs/storybook-data/alluvial-data.ts, packages/lib/src/types/alluvial.ts
Closes #314 
> - Add `offset` property to `AlluvialNode` interface
> - Calculate node position if offset is valid
> - Update documentation and add Storybook example
> - Missing unit tests
=> ✨ Add node offset property

CHANGELOG.md, package.json, packages/vue2/package.json, packages/vue3/package.json
- ✨ Add node offset property [`23788da`](https://github.com/Adyen/lume/commit/23788da580e00435eb7d59d5c92ead23ece90a84)
- 📝 Update README [`d7cbdca`](https://github.com/Adyen/lume/commit/d7cbdcaec1b7377d3b06fb7d5194aaa6eba0c1a1)
- ✅ Add node offset unit test [`1e2e93d`](https://github.com/Adyen/lume/commit/1e2e93d4ca308dc6a91a22466eb5b78411124b0c)
- 📝 Update package.json & LICENSE [`3dc0419`](https://github.com/Adyen/lume/commit/3dc0419f1454296f7c9681d4992c7c82d5ca5e64)
- 🩹 Fix Storybook sidebar logo [`99850a7`](https://github.com/Adyen/lume/commit/99850a7ce5b0ad27bee5f94fc81f1622e9851a76)
- 📝 Add package READMEs [`443ea56`](https://github.com/Adyen/lume/commit/443ea569fab5743df374e6fb750a3078f793b9c0)
=> 🔖 Release v1.1.0

CHANGELOG.md, package.json, packages/vue2/package.json, packages/vue3/package.json
Relates to #269 
Added a provision to capture interaction events in lume tooltip.
>
=> 🔖 Release v1.2.0

.eslintrc.cjs, packages/lib/src/components/charts/lume-alluvial-diagram/lume-alluvial-diagram.vue, packages/lib/src/components/charts/lume-bar-chart/lume-bar-chart.vue, packages/lib/src/components/charts/lume-grouped-bar-chart/lume-grouped-bar-chart.vue, packages/lib/src/components/charts/lume-line-chart/lume-line-chart.vue, packages/lib/src/components/charts/lume-single-bar-chart/lume-single-bar-chart.vue, packages/lib/src/components/charts/lume-sparkline-chart/lume-sparkline-chart.vue, packages/lib/src/components/charts/lume-stacked-bar-chart/lume-stacked-bar-chart.vue, packages/lib/src/components/core/lume-chart/lume-chart.vue, packages/lib/src/components/groups/lume-bar-group/lume-bar-group.vue, packages/lib/src/composables/events.ts, packages/lib/typings/vue-shims.d.ts, packages/vue2/vite.config.ts, packages/vue3/vite.config.ts, packages/vue3/vitest.config.ts
Fixes #238 
> - Added event propagator function to all chart components (Vue 2 only)
> - Added a global variable for the Vue version
>
=> 🐛 Fix event emission for Vue 2

CHANGELOG.md, package.json, packages/vue2/package.json, packages/vue3/package.json
Relates to #325 
Supports grouped chart with varied number of data points.
> Add a brief description
=> 🔖 Release v1.3.0

CHANGELOG.md, git-hooks/commit-msg, package.json, packages/vue2/package.json, packages/vue3/package.json
Relates to #331 #332 
- Using custom events for Vue 2 internal events instead of event bus
- Added group events to listen on group related events.
- Storybook Vue 2 console error fixes
=> 🔖 Release v1.4.0

CHANGELOG.md, package.json, packages/vue2/package.json, packages/vue3/package.json
- For grouped charts all the items need not have to be of same length.
- Marking index as invalid only if its greater than all the items.
=> 🔖 Release v1.5.3

package.json, packages/lib/package.json, packages/lib/src/components/charts/lume-bar-chart/lume-bar-chart.vue, packages/lib/src/components/charts/lume-sparkline-chart/composables/sparkline-area.ts, packages/lib/src/components/charts/lume-sparkline-chart/lume-sparkline.spec.ts, packages/lib/src/components/core/lume-chart-container/lume-chart-container.vue, packages/lib/src/components/core/lume-point/lume-point.vue, packages/lib/src/components/groups/lume-alluvial-group/composables/alluvial-graph.ts, packages/lib/src/components/groups/lume-alluvial-group/lume-alluvial-group.vue, packages/lib/src/components/groups/lume-bar-group/composables/stacked-mixin.ts, packages/lib/src/composables/events.ts, packages/lib/src/composables/scales.ts, packages/lib/src/plugin.ts, packages/lib/src/types/alluvial.ts, packages/lib/src/types/events.ts, packages/lib/src/utils/constants.ts, packages/lib/src/utils/helpers.ts, packages/lib/tsconfig.d.json, packages/storybook-utils/package.json, packages/vue2/package.json, packages/vue2/tsconfig.d.json, packages/vue3/package.json, packages/vue3/tsconfig.d.json, pnpm-lock.yaml, tsconfig.json
Closes #330 
> - Added `vue-tsc` to generate type declarations
> - Fixed existing TS errors
> - Now ships with `@types`!
=> 🏷️ Reintroduce type declarations; Fix TS errors

CHANGELOG.md, package.json, packages/vue2/package.json, packages/vue3/package.json
- 🏷️ Reintroduce type declarations; Fix TS errors [`439e336`](https://github.com/Adyen/lume/commit/439e3368f5b507d1921fc4112794bed0777f4801)
- ✨ Add nodeLabelMaxWidth option to alluvial [`ea40c45`](https://github.com/Adyen/lume/commit/ea40c45cb3730786914adf85e4deaa89f9ac59ae)
- 🚸 Replacing the error with warning if index is not present in group. [`4667c03`](https://github.com/Adyen/lume/commit/4667c03a613db09062ee839adef45d56af9f20f9)
- 📝 Update Stories; Fix maxWidth initial value [`0ff0a00`](https://github.com/Adyen/lume/commit/0ff0a0028b03cbf794e2b602fcd523e18e881ba6)
=> 🔖 Release v1.6.0

CHANGELOG.md, package.json, packages/vue2/package.json, packages/vue3/package.json
- 🐛 Fix wrong types file path [`9f152dc`](https://github.com/Adyen/lume/commit/9f152dc7e1a64f3503d07bdf0ae173d867becb7b)
=> 🔖 Release v1.6.1

CHANGELOG.md, package.json, packages/vue2/package.json, packages/vue3/package.json
- 🐛 Fix alluvial node min. height in derived nodes [`d71b702`](https://github.com/Adyen/lume/commit/d71b702651a3b2ac1eee9cd581e148d1c1b961a4)
- 🐛 Fix unhandled line-group null value cases [`909b672`](https://github.com/Adyen/lume/commit/909b672addf3f11dd91769b2feb69512ef2f43e3)
- 🐛 Make skip option reactive [`eefa96e`](https://github.com/Adyen/lume/commit/eefa96e033137ba350abbed8fcd3d472c24751ed)
- 💄 Update tooltip value spacing [`568ae4f`](https://github.com/Adyen/lume/commit/568ae4f6cd8ab3a426a4c7a30c70e13e38e3dca4)
=> 🔖 Release v1.6.5

packages/lib/src/components/core/lume-axis/lume-axis.vue
Fixes #377
Added a watcher on `containerSize` - if it changes, recalculate the gridlines.
This is needed for cases where the container width changes, so the Y gridlines need to update, but the Y scale doesn't change since the height is the same
=> 🐛 Update gridlines on container size change

.github/ISSUE_TEMPLATE/problem-report.yml
Closes #378
Added two fields to the problem report template: package(s) and version(s)
=> 🔧 Add package & version fields in problem report template

CHANGELOG.md, package.json, packages/lib/src/docs/storybook-data/base-data.ts, packages/vue2/package.json, packages/vue3/package.json
- 🐛 Fix empty data/labels handling [`d5dca98`](https://github.com/Adyen/lume/commit/d5dca9899ea03a433672df32537bc107ccc23492)
- 🐛 Fix wrong assumption on external hover [`ca3f936`](https://github.com/Adyen/lume/commit/ca3f936e238467c7583a66242cf59fa3b714ed79)
- ✨ Introduce inverse property/option in lume-tooltip [`f510005`](https://github.com/Adyen/lume/commit/f5100056a33808b30a6368f064901dda746a8a14)
- 🐛 Fix handling datasets with empty values [`0a06efe`](https://github.com/Adyen/lume/commit/0a06efe33ff2e40ba38083dc5b5ccbc93bfbc7e8)
- 🐛 Update gridlines on container size change [`294a473`](https://github.com/Adyen/lume/commit/294a4734d1dab4074fc6d2e26b273b3ecfbd4d1b)
- 🔧 Add package & version fields in problem report template [`523e8f4`](https://github.com/Adyen/lume/commit/523e8f4c9ec9b0 …
=> 🔖 Release v1.7.0

CHANGELOG.md, package.json, packages/vue2/package.json, packages/vue3/package.json
- ✨ Add lume-alluvial-node-header component [`8cbfbf2`](https://github.com/Adyen/lume/commit/8cbfbf2eb2afd4ff18afaac731c0288a125940d8)
- 🔧 Add triage label to issue templates [`c4e9771`](https://github.com/Adyen/lume/commit/c4e97713c57d43f17a88dec4783fb3a99f7b2342)
- 🩹 Fix the horizontal stacked bar chart default options [`6f32ccf`](https://github.com/Adyen/lume/commit/6f32ccfb0a3434569897cccb31e3f8950de9fb87)
=> 🔖 Release v1.8.0

CHANGELOG.md, package.json, packages/vue2/package.json, packages/vue3/package.json
- 🐛 Add missing color values in constants [`7bbf38b`](https://github.com/Adyen/lume/commit/7bbf38b5e026711281a3fcde9fe05c7c89b3f952)
=> 🔖 Release v1.9.1

CHANGELOG.md, package.json, packages/vue2/package.json, packages/vue3/package.json
- 🐛 Fix lume-tooltip use v-if instead of v-show [`9ece713`](https://github.com/Adyen/lume/commit/9ece7139051be5f6ad80088630d77b351d4fad11)
- ✅ Fix unit tests [`203feb0`](https://github.com/Adyen/lume/commit/203feb0289df3eb6a732e6a64980b3611f778442)
=> 🔖 Release v1.9.3

CHANGELOG.md, git-hooks/commit-msg, package.json, packages/vue2/package.json, packages/vue3/package.json
=> 🔖 Release v1.9.4

CHANGELOG.md, package.json, packages/vue2/package.json, packages/vue3/package.json
=> 🔖 Release v1.9.5

CHANGELOG.md, package.json, packages/vue2/package.json, packages/vue3/package.json
- 💄 Update various Lume styles [`268fcfb`](https://github.com/Adyen/lume/commit/268fcfb1186f44802fc147f679914269d614b8c8)
=> 🔖 Release v1.10.0

packages/lib/src/playground/bar-sparkline.stories.ts, packages/lib/src/playground/bar-sparkline.vue
- Updated the `bar-sparkline` playground example with new design.
--
=> 📝 Update bar-sparkline playground example

CHANGELOG.md, package.json, packages/vue2/package.json, packages/vue3/package.json
- ⬆️ Update dependency sass to v1.76.0 [`214cd83`](https://github.com/Adyen/lume/commit/214cd83c338a1d3de61679a24cd1734723fa3e14)
- 📝 Update bar-sparkline playground example [`38e4fb9`](https://github.com/Adyen/lume/commit/38e4fb93af07aa89b3210a449c19043b636d031d)
- 🐛 Convert bar transform-origin to rem [`810ffb3`](https://github.com/Adyen/lume/commit/810ffb3e365ec2b4918ae63c2944b7f830b75827)
=> 🔖 Release v1.10.1

packages/lib/src/index.ts
Added an export for the composables. This is useful for custom implementation within `lume-chart`
- (optional) Add additional information
=> 🩹 Export composables

CHANGELOG.md, package.json, packages/vue2/package.json, packages/vue3/package.json
- 🩹 Export composables [`b06d25c`](https://github.com/Adyen/lume/commit/b06d25c786f6ee1bc06776df4b316b34f766cfc4)
=> 🔖 Release v1.11.0

packages/vue3/package.json, pnpm-lock.yaml
Allow Vue >=3.x to use Lume
- (optional) Add additional information
=> 🚀 Updated peer dependency of vue in Lume Vue 3 package

CHANGELOG.md, package.json, packages/vue2/package.json, packages/vue3/package.json
- ⏪️ Revert "Convert bar transform-origin to rem" [`0eb3300`](https://github.com/Adyen/lume/commit/0eb33004e3551ac19fa49d6411dc715e2c5a1c65)
=> 🔖 Release v1.11.4

package.json, pnpm-lock.yaml
Pins the `vite` version to a specific, non-vulnerable version.
---
=> 📌 Pin vite version in pnpm catalog

eslint.config.js, package.json, pnpm-lock.yaml
Skipped linting for generated code
=> 🚨Skipped linting for generated code; Bumped release-it

CHANGELOG.md, package.json, packages/vue2/package.json, packages/vue3/package.json
* 🐛 Fix linear yScale for an all-negative domain by @joao-m-santos in https://github.com/Adyen/lume/pull/623
=> 🔖 Release v1.11.5

package.json, packages/vue2/package.json, packages/vue3/package.json, pnpm-lock.yaml
Upgraded dependency versions
This fixes the currently reported security issues
=> ⬆️ Upgrade dependency versions to fix security issues
